// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: calculation_history.
// - Entity ID: 102019ac98f66c17ed09c08582987cfae35.
// - Entity Version: 102019acae7a686722a97950c130aec065f.
// - Task ID: 6929b4093eae0296d77f081a.
// - Task Root ID: 69295b334865aaabce3c1a3e.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for CalculationHistoryMode
 */
export enum CalculationHistoryMode {
  Unspecified = 0,
  Manual = 1,
  AI = 2,
}



/**
 * Interface for CalculationHistoryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface CalculationHistoryModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  calculation_time: string;
  mode: CalculationHistoryMode;
  brand_name?: string | null;
  budget?: number | null;
  campaign_goal?: string | null;
  brand_awareness: number;
  market_saturation: number;
  campaign_goal_param: number;
  target_audience: number;
  product_complexity: number;
  message_complexity: number;
  calculated_frequency: number;
}

/**
 * ORM class for CalculationHistory entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class CalculationHistoryORM {
  private static instance: CalculationHistoryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac98f66c17ed09c08582987cfae35';
    this.entityName = 'calculation_history';
    this.entityVersion = '102019acae7a686722a97950c130aec065f';
    this.taskId = '6929b4093eae0296d77f081a';
    this.taskRootId = '69295b334865aaabce3c1a3e';
  }

  /**
   * Get singleton instance of CalculationHistoryORM
   */
  public static getInstance(): CalculationHistoryORM {
    if (!CalculationHistoryORM.instance) {
      CalculationHistoryORM.instance = new CalculationHistoryORM();
    }
    
    return CalculationHistoryORM.instance;
  }

  /**
   * Get all CalculationHistory records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllCalculationHistory(): Promise<CalculationHistoryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new CalculationHistory record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertCalculationHistory(data: CalculationHistoryModel[]): Promise<CalculationHistoryModel[]> {
    const structured = data.map((item) => CreateData(CalculationHistoryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all CalculationHistory records
   */
  async purgeAllCalculationHistory(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List CalculationHistory records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listCalculationHistory(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[CalculationHistoryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get calculation_history by Id index
   * This function gets data by index.
   */
  async getCalculationHistoryById(
    id: string,
  ): Promise<CalculationHistoryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) calculation_history by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCalculationHistoryById(
    id: string,
    data: CalculationHistoryModel
  ): Promise<CalculationHistoryModel[]> {
    const index = createIndexId(
      id
    );

    const values = CalculationHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete calculation_history by Id index
   */
  async deleteCalculationHistoryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get calculation_history by DataCreator index
   * This function gets data by index.
   */
  async getCalculationHistoryByDataCreator(
    data_creator: string,
  ): Promise<CalculationHistoryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) calculation_history by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCalculationHistoryByDataCreator(
    data_creator: string,
    data: CalculationHistoryModel
  ): Promise<CalculationHistoryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = CalculationHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete calculation_history by DataCreator index
   */
  async deleteCalculationHistoryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get calculation_history by DataUpdater index
   * This function gets data by index.
   */
  async getCalculationHistoryByDataUpdater(
    data_updater: string,
  ): Promise<CalculationHistoryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) calculation_history by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCalculationHistoryByDataUpdater(
    data_updater: string,
    data: CalculationHistoryModel
  ): Promise<CalculationHistoryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = CalculationHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete calculation_history by DataUpdater index
   */
  async deleteCalculationHistoryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get calculation_history by CalculationTimeDataCreator index
   * This function gets data by index.
   */
  async getCalculationHistoryByCalculationTimeDataCreator(
    calculation_time: string,
    data_creator: string,
  ): Promise<CalculationHistoryModel[]> {
    const index = createIndexCalculationTimeDataCreator(
      calculation_time,
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) calculation_history by CalculationTimeDataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCalculationHistoryByCalculationTimeDataCreator(
    calculation_time: string,
    data_creator: string,
    data: CalculationHistoryModel
  ): Promise<CalculationHistoryModel[]> {
    const index = createIndexCalculationTimeDataCreator(
      calculation_time,
      data_creator
    );

    const values = CalculationHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete calculation_history by CalculationTimeDataCreator index
   */
  async deleteCalculationHistoryByCalculationTimeDataCreator(
    calculation_time: string,
    data_creator: string
  ): Promise<void> {
    const index = createIndexCalculationTimeDataCreator(
      calculation_time,
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to CalculationHistoryModel data array
   */
  private resultToData(values: Data[]): CalculationHistoryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return CalculationHistoryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as CalculationHistoryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized CalculationHistoryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is CalculationHistoryModel => item !== null);
  }
}

/**
 * Convert CalculationHistoryModel data to Value array
 */
function CalculationHistoryModelToValues(data: CalculationHistoryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'calculation_time', type: DataType.string, defaultValue: '' },
    { key: 'mode', type: DataType.enumeration, defaultValue: 0 },
    { key: 'brand_name', type: DataType.string, defaultValue: null },
    { key: 'budget', type: DataType.number, defaultValue: null },
    { key: 'campaign_goal', type: DataType.string, defaultValue: null },
    { key: 'brand_awareness', type: DataType.number, defaultValue: 0 },
    { key: 'market_saturation', type: DataType.number, defaultValue: 0 },
    { key: 'campaign_goal_param', type: DataType.number, defaultValue: 0 },
    { key: 'target_audience', type: DataType.number, defaultValue: 0 },
    { key: 'product_complexity', type: DataType.number, defaultValue: 0 },
    { key: 'message_complexity', type: DataType.number, defaultValue: 0 },
    { key: 'calculated_frequency', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof CalculationHistoryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to CalculationHistoryModel data
 */
function CalculationHistoryModelFromValues(values: Value[]): CalculationHistoryModel {
  const data: Partial<CalculationHistoryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'calculation_time':
        data.calculation_time = ParseValue(value, DataType.string) as string;
        break;
      case 'mode':
        data.mode = ParseValue(value, DataType.enumeration) as CalculationHistoryMode;
        break;
      case 'brand_name':
        data.brand_name = ParseValue(value, DataType.string) as string | null;
        break;
      case 'budget':
        data.budget = ParseValue(value, DataType.number) as number | null;
        break;
      case 'campaign_goal':
        data.campaign_goal = ParseValue(value, DataType.string) as string | null;
        break;
      case 'brand_awareness':
        data.brand_awareness = ParseValue(value, DataType.number) as number;
        break;
      case 'market_saturation':
        data.market_saturation = ParseValue(value, DataType.number) as number;
        break;
      case 'campaign_goal_param':
        data.campaign_goal_param = ParseValue(value, DataType.number) as number;
        break;
      case 'target_audience':
        data.target_audience = ParseValue(value, DataType.number) as number;
        break;
      case 'product_complexity':
        data.product_complexity = ParseValue(value, DataType.number) as number;
        break;
      case 'message_complexity':
        data.message_complexity = ParseValue(value, DataType.number) as number;
        break;
      case 'calculated_frequency':
        data.calculated_frequency = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as CalculationHistoryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for CalculationTimeDataCreator fields
 */
function createIndexCalculationTimeDataCreator(
  calculation_time: string,
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, calculation_time, 'calculation_time'),
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['calculation_time', 'data_creator'],
    values
  };
}

export default CalculationHistoryORM;